# This sample config contains all fields supported by ravenML core and the instance plugin.
# Plugin specific configuration is located in the plugin field.

dataset: carson_instance_tester
overwrite_local: True
artifact_path: '~/Desktop/test'
# options are:
#   'stop' to stop the instance
#   'terminate' to terminate the instance
#   any other string: keep instance running
# if this field is not set, the default is 'stop'
ec2_policy: none                    
metadata:
    created_by: Carson Schubert
    comments: no thanks
plugin:
    verbose: true
    comet: false
    model: mask_rcnn_inception_v2_coco  # only one supported rn
    optimizer: Momentum                 # only one supported rn
    no_validate: true                   # do not perform validation after training
    # NOTE: if use_default_config is true, hyperparameters are IGNORED
    use_default_config: false
    hyperparameters:
        train_steps: 25
    