# This sample config contains all fields supported by ravenML core and the keypoints regression plugin.
# Plugin specific configuration is located in the plugin field.

dataset: cygnus_10k_keypoints_pose
overwrite_local: False
artifact_path: './artifacts'
ec2_policy: stop
metadata:
    created_by: Kevin Black
    comments: no thanks
plugin:
    keypoints: 20
    fc_width: 512
    fc_count: 1
    batch_size: 5
    cache_train_data: False
    prefetch_num_batches: 10
    crop_size: 224
    shuffle_buffer_size: 20000
    model_arch: mobilenet
    model_init_weights: imagenet
    model_unet_params: {}
    phases:
        - optimizer: Adam
          optimizer_args:
            learning_rate: 0.001
          epochs: 100
          start_layer: input_1
    pnp_focal_length: 1422.0
    dropout: 0.0
