dataset: click_test
overwrite_local: True
artifact_path: '~/Desktop/test'
# options are:
#   'stop' to stop the instance
#   'terminate' to terminate the instance
#   any other string: keep instance running
# if this field is not set, the default is 'stop'
ec2_policy: none                    
metadata:
    created_by: Carson Schubert
    comments: no thanks
plugin:
    - model_variant: mobilenet_v2
    #- atrous_rates: 6
    #- atrous_rates: 12
    #- atrous_rates: 18
    #- decoder_output_stride: 4
    - output_stride: 16
    - train_crop_size: 721,961
    - train_batch_size: 1
    - fine_tune_batch_norm: True
    # requires full filepath - ~ is NOT converted
    - tf_initial_checkpoint: /home/carson/tsl/pipeline/ravenML-train-plugins/rmltraintfsemantic/deeplabv3_mnv2_dm05_pascal_trainaug/model.ckpt
    - depth_multiplier: 0.5
    - save_summaries_images: True
    - save_summaries_secs: 20
    - min_scale_factor: 0.5
    - max_scale_factor: 2
    - hard_example_mining_step: 1
    - top_k_percent_pixels: 0.05
